/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  BodyLoginAuthTokenPost,
  HTTPValidationError,
  Token,
  User,
  UserChangePassword,
  UserCreate
} from '.././types';

import { axiosCustom } from '.././mutator/axiosCustom';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Register
 */
export const registerAuthRegisterPost = (
    userCreate: UserCreate,
 options?: SecondParameter<typeof axiosCustom>,signal?: AbortSignal
) => {
      
      
      return axiosCustom<User>(
      {url: `/auth/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userCreate, signal
    },
      options);
    }
  


export const getRegisterAuthRegisterPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerAuthRegisterPost>>, TError,{data: UserCreate}, TContext>, request?: SecondParameter<typeof axiosCustom>}
): UseMutationOptions<Awaited<ReturnType<typeof registerAuthRegisterPost>>, TError,{data: UserCreate}, TContext> => {

const mutationKey = ['registerAuthRegisterPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof registerAuthRegisterPost>>, {data: UserCreate}> = (props) => {
          const {data} = props ?? {};

          return  registerAuthRegisterPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RegisterAuthRegisterPostMutationResult = NonNullable<Awaited<ReturnType<typeof registerAuthRegisterPost>>>
    export type RegisterAuthRegisterPostMutationBody = UserCreate
    export type RegisterAuthRegisterPostMutationError = HTTPValidationError

    /**
 * @summary Register
 */
export const useRegisterAuthRegisterPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerAuthRegisterPost>>, TError,{data: UserCreate}, TContext>, request?: SecondParameter<typeof axiosCustom>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof registerAuthRegisterPost>>,
        TError,
        {data: UserCreate},
        TContext
      > => {

      const mutationOptions = getRegisterAuthRegisterPostMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Login
 */
export const loginAuthTokenPost = (
    bodyLoginAuthTokenPost: BodyLoginAuthTokenPost,
 options?: SecondParameter<typeof axiosCustom>,signal?: AbortSignal
) => {
      
      const formUrlEncoded = new URLSearchParams();
if(bodyLoginAuthTokenPost.grant_type !== undefined && bodyLoginAuthTokenPost.grant_type !== null) {
 formUrlEncoded.append(`grant_type`, bodyLoginAuthTokenPost.grant_type)
 }
formUrlEncoded.append(`username`, bodyLoginAuthTokenPost.username)
formUrlEncoded.append(`password`, bodyLoginAuthTokenPost.password)
if(bodyLoginAuthTokenPost.scope !== undefined) {
 formUrlEncoded.append(`scope`, bodyLoginAuthTokenPost.scope)
 }
if(bodyLoginAuthTokenPost.client_id !== undefined && bodyLoginAuthTokenPost.client_id !== null) {
 formUrlEncoded.append(`client_id`, bodyLoginAuthTokenPost.client_id)
 }
if(bodyLoginAuthTokenPost.client_secret !== undefined && bodyLoginAuthTokenPost.client_secret !== null) {
 formUrlEncoded.append(`client_secret`, bodyLoginAuthTokenPost.client_secret)
 }

      return axiosCustom<Token>(
      {url: `/auth/token`, method: 'POST',
      headers: {'Content-Type': 'application/x-www-form-urlencoded', },
       data: formUrlEncoded, signal
    },
      options);
    }
  


export const getLoginAuthTokenPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginAuthTokenPost>>, TError,{data: BodyLoginAuthTokenPost}, TContext>, request?: SecondParameter<typeof axiosCustom>}
): UseMutationOptions<Awaited<ReturnType<typeof loginAuthTokenPost>>, TError,{data: BodyLoginAuthTokenPost}, TContext> => {

const mutationKey = ['loginAuthTokenPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loginAuthTokenPost>>, {data: BodyLoginAuthTokenPost}> = (props) => {
          const {data} = props ?? {};

          return  loginAuthTokenPost(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LoginAuthTokenPostMutationResult = NonNullable<Awaited<ReturnType<typeof loginAuthTokenPost>>>
    export type LoginAuthTokenPostMutationBody = BodyLoginAuthTokenPost
    export type LoginAuthTokenPostMutationError = HTTPValidationError

    /**
 * @summary Login
 */
export const useLoginAuthTokenPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginAuthTokenPost>>, TError,{data: BodyLoginAuthTokenPost}, TContext>, request?: SecondParameter<typeof axiosCustom>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof loginAuthTokenPost>>,
        TError,
        {data: BodyLoginAuthTokenPost},
        TContext
      > => {

      const mutationOptions = getLoginAuthTokenPostMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary Change Password
 */
export const changePasswordAuthChangePasswordPut = (
    userChangePassword: UserChangePassword,
 options?: SecondParameter<typeof axiosCustom>,) => {
      
      
      return axiosCustom<unknown>(
      {url: `/auth/change-password`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: userChangePassword
    },
      options);
    }
  


export const getChangePasswordAuthChangePasswordPutMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changePasswordAuthChangePasswordPut>>, TError,{data: UserChangePassword}, TContext>, request?: SecondParameter<typeof axiosCustom>}
): UseMutationOptions<Awaited<ReturnType<typeof changePasswordAuthChangePasswordPut>>, TError,{data: UserChangePassword}, TContext> => {

const mutationKey = ['changePasswordAuthChangePasswordPut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof changePasswordAuthChangePasswordPut>>, {data: UserChangePassword}> = (props) => {
          const {data} = props ?? {};

          return  changePasswordAuthChangePasswordPut(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ChangePasswordAuthChangePasswordPutMutationResult = NonNullable<Awaited<ReturnType<typeof changePasswordAuthChangePasswordPut>>>
    export type ChangePasswordAuthChangePasswordPutMutationBody = UserChangePassword
    export type ChangePasswordAuthChangePasswordPutMutationError = HTTPValidationError

    /**
 * @summary Change Password
 */
export const useChangePasswordAuthChangePasswordPut = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changePasswordAuthChangePasswordPut>>, TError,{data: UserChangePassword}, TContext>, request?: SecondParameter<typeof axiosCustom>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof changePasswordAuthChangePasswordPut>>,
        TError,
        {data: UserChangePassword},
        TContext
      > => {

      const mutationOptions = getChangePasswordAuthChangePasswordPutMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    