/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { BodyLoginAuthTokenPostGrantType } from './bodyLoginAuthTokenPostGrantType';
import type { BodyLoginAuthTokenPostClientId } from './bodyLoginAuthTokenPostClientId';
import type { BodyLoginAuthTokenPostClientSecret } from './bodyLoginAuthTokenPostClientSecret';

export interface BodyLoginAuthTokenPost {
  grant_type?: BodyLoginAuthTokenPostGrantType;
  username: string;
  password: string;
  scope?: string;
  client_id?: BodyLoginAuthTokenPostClientId;
  client_secret?: BodyLoginAuthTokenPostClientSecret;
}
