/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { CategoryModelId } from './categoryModelId';

export interface CategoryModel {
  id?: CategoryModelId;
  name: string;
  userId: string;
}
