/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ExpenseOutCategoryName } from './expenseOutCategoryName';
import type { ExpenseOutDescription } from './expenseOutDescription';

export interface ExpenseOut {
  id: string;
  amount: number;
  category_id: string;
  category_name: ExpenseOutCategoryName;
  date: string;
  description: ExpenseOutDescription;
}
