/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ExpenseModelId } from './expenseModelId';
import type { ExpenseModelDescription } from './expenseModelDescription';

export interface ExpenseModel {
  id?: ExpenseModelId;
  amount: number;
  categoryId: string;
  date: string;
  description: ExpenseModelDescription;
  userId: string;
}
