/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ExpenseCreateDate } from './expenseCreateDate';
import type { ExpenseCreateDescription } from './expenseCreateDescription';

export interface ExpenseCreate {
  /** */
  amount: number;
  category_id: string;
  date?: ExpenseCreateDate;
  description?: ExpenseCreateDescription;
}
