/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { IncomeCreateSource } from './incomeCreateSource';
import type { IncomeCreateDate } from './incomeCreateDate';
import type { IncomeCreateDescription } from './incomeCreateDescription';

export interface IncomeCreate {
  /** */
  amount: number;
  source?: IncomeCreateSource;
  date?: IncomeCreateDate;
  description?: IncomeCreateDescription;
}
