/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { IncomeOutSource } from './incomeOutSource';
import type { IncomeOutDescription } from './incomeOutDescription';

export interface IncomeOut {
  id: string;
  amount: number;
  source: IncomeOutSource;
  date: string;
  description: IncomeOutDescription;
}
