/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { IncomeModelId } from './incomeModelId';
import type { IncomeModelSource } from './incomeModelSource';
import type { IncomeModelDescription } from './incomeModelDescription';

export interface IncomeModel {
  id?: IncomeModelId;
  amount: number;
  source: IncomeModelSource;
  date: string;
  description: IncomeModelDescription;
  userId: string;
}
