/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ListExpensesExpensesGetParams = {
start_date?: string | null;
end_date?: string | null;
skip?: number;
limit?: number;
};
